apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- if eq .Release.Namespace "lmc-dev" }}
  lineConfigChannelChannelAccessToken: {{ index .Values.secret.data.lineConfigChannelChannelAccessToken 1 | b64enc }}
  lineConfigChannelClientId: {{ index .Values.secret.data.lineConfigChannelClientId 1 | b64enc }}
  lineConfigChannelSecretId: {{ index .Values.secret.data.lineConfigChannelSecretId 1 | b64enc }}
  lineConfigLineLoginSecretId: {{ index .Values.secret.data.lineConfigLineLoginSecretId 1 | b64enc }}
  lineConfigLineLoginClientId: {{ index .Values.secret.data.lineConfigLineLoginClientId 1 | b64enc }}
  lineConfigLineLoginRedirectUri: {{ index .Values.secret.data.lineConfigLineLoginRedirectUri 1 | b64enc }}
  rabbitmqHost: {{ index .Values.secret.data.rabbitmqHost 1 | b64enc }}
  mongoHost: {{ index .Values.secret.data.mongoHost 1 | b64enc }}
  {{- else if eq .Release.Namespace "lmc-prod" }}
  lineConfigChannelChannelAccessToken: {{ index .Values.secret.data.lineConfigChannelChannelAccessToken 2 | b64enc }}
  lineConfigChannelClientId: {{ index .Values.secret.data.lineConfigChannelClientId 2 | b64enc }}
  lineConfigChannelSecretId: {{ index .Values.secret.data.lineConfigChannelSecretId 2 | b64enc }}
  lineConfigLineLoginSecretId: {{ index .Values.secret.data.lineConfigLineLoginSecretId 2 | b64enc }}
  lineConfigLineLoginClientId: {{ index .Values.secret.data.lineConfigLineLoginClientId 2 | b64enc }}
  lineConfigLineLoginRedirectUri: {{ index .Values.secret.data.lineConfigLineLoginRedirectUri 2 | b64enc }}
  rabbitmqHost: {{ index .Values.secret.data.rabbitmqHost 2 | b64enc }}
  mongoHost: {{ index .Values.secret.data.mongoHost 2 | b64enc }}
  {{- else }}
  lineConfigChannelChannelAccessToken: {{ index .Values.secret.data.lineConfigChannelChannelAccessToken 0 | b64enc }}
  lineConfigChannelClientId: {{ index .Values.secret.data.lineConfigChannelClientId 0 | b64enc }}
  lineConfigChannelSecretId: {{ index .Values.secret.data.lineConfigChannelSecretId 0 | b64enc }}
  lineConfigLineLoginSecretId: {{ index .Values.secret.data.lineConfigLineLoginSecretId 0 | b64enc }}
  lineConfigLineLoginClientId: {{ index .Values.secret.data.lineConfigLineLoginClientId 0 | b64enc }}
  lineConfigLineLoginRedirectUri: {{ index .Values.secret.data.lineConfigLineLoginRedirectUri 0 | b64enc }}
  rabbitmqHost: {{ index .Values.secret.data.rabbitmqHost 0 | b64enc }}
  mongoHost: {{ index .Values.secret.data.mongoHost 0 | b64enc }}
  {{- end }}