apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  objectStorageConfigServiceUrl: {{ .Values.secret.data.objectStorageConfigServiceUrl | b64enc }}
  objectStorageConfigAccessKey: {{ .Values.secret.data.objectStorageConfigAccessKey | b64enc }}
  objectStorageConfigSecretKey: {{ .Values.secret.data.objectStorageConfigSecretKey | b64enc }}
  objectStorageConfigBucketName: {{ .Values.secret.data.objectStorageConfigBucketName | b64enc }}
  {{- if eq .Release.Namespace "lmc-dev" }}
  lineConfigChannelChannelAccessToken: {{ index .Values.secret.data.lineConfigChannelChannelAccessToken 1 | b64enc }}
  lineConfigChannelClientId: {{ index .Values.secret.data.lineConfigChannelClientId 1 | b64enc }}
  lineConfigChannelSecretId: {{ index .Values.secret.data.lineConfigChannelSecretId 1 | b64enc }}
  rabbitmqHost: {{ index .Values.secret.data.rabbitmqHost 1 | b64enc }}
  mongoHost: {{ index .Values.secret.data.mongoHost 1 | b64enc }}
  {{- else if eq .Release.Namespace "lmc-prod" }}
  lineConfigChannelChannelAccessToken: {{ index .Values.secret.data.lineConfigChannelChannelAccessToken 2 | b64enc }}
  lineConfigChannelClientId: {{ index .Values.secret.data.lineConfigChannelClientId 2 | b64enc }}
  lineConfigChannelSecretId: {{ index .Values.secret.data.lineConfigChannelSecretId 2 | b64enc }}
  rabbitmqHost: {{ index .Values.secret.data.rabbitmqHost 2 | b64enc }}
  mongoHost: {{ index .Values.secret.data.mongoHost 2 | b64enc }}
  {{- else }}
  lineConfigChannelChannelAccessToken: {{ index .Values.secret.data.lineConfigChannelChannelAccessToken 0 | b64enc }}
  lineConfigChannelClientId: {{ index .Values.secret.data.lineConfigChannelClientId 0 | b64enc }}
  lineConfigChannelSecretId: {{ index .Values.secret.data.lineConfigChannelSecretId 0 | b64enc }}
  rabbitmqHost: {{ index .Values.secret.data.rabbitmqHost 0 | b64enc }}
  mongoHost: {{ index .Values.secret.data.mongoHost 0 | b64enc }}
  {{- end }}